<?php

use Illuminate\Database\Seeder;

class GamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('games')->delete();
        
        \DB::table('games')->insert(array (
            0 => 
            array (
                'gameID' => 1,
                'gameName' => 'anime_fighting_jam_wing',
                'gameDesc' => 'Anime Fight',
                'scoreID' => 0,
                'gameURL' => 'games/anime_fighting_jam_wing/anime_fighting_jam_wing.swf',
                'thumbnail' => 'images/Games/animeFightingJam.png',
                'fthumbnail' => 'images/Featured Games/killerCubes.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 714,
                'height' => 714,
            ),
            1 => 
            array (
                'gameID' => 2,
                'gameName' => 'avatar_arena',
                'gameDesc' => 'Arena Avatar',
                'scoreID' => 0,
                'gameURL' => 'games/avatar_arena/avatar_arena.swf',
                'thumbnail' => 'images/Games/avatarArena.png',
                'fthumbnail' => 'images/Featured Games/4Square.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            2 => 
            array (
                'gameID' => 3,
                'gameName' => 'avatar_fortress_fight_2',
                'gameDesc' => 'Avatar',
                'scoreID' => 0,
                'gameURL' => 'games/avatar_fortress_fight_2/avatar_fortress_fight_2.swf',
                'thumbnail' => 'images/Games/avatar-fortress-fight2.png',
                'fthumbnail' => 'images/Featured Games/DotsTrix.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            3 => 
            array (
                'gameID' => 4,
                'gameName' => 'box_head_2_play',
                'gameDesc' => 'pew pew',
                'scoreID' => 0,
                'gameURL' => 'games/box_head_2_play/box_head_2play.swf',
                'thumbnail' => 'images/Games/boxHead.png',
                'fthumbnail' => 'images/Featured Games/Feature2.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            4 => 
            array (
                'gameID' => 5,
                'gameName' => 'catch_the_ball',
                'gameDesc' => 'ball',
                'scoreID' => 0,
                'gameURL' => 'games/catch_the_ball/catch_the_ball.swf',
                'thumbnail' => 'images/Games/catchTheBall.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            5 => 
            array (
                'gameID' => 7,
                'gameName' => 'combat_tournament_legends',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/combat_tournament_legends/combat_tournament_legends.swf',
                'thumbnail' => 'images/Games/combatTournament.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            6 => 
            array (
                'gameID' => 10,
                'gameName' => 'detonate2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/detonate2/detonate2.swf',
                'thumbnail' => 'images/Games/detonate2.png',
                'fthumbnail' => 'images/Featured Games/Feature2.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 450,
                'height' => 550,
            ),
            7 => 
            array (
                'gameID' => 13,
                'gameName' => 'fireboy_and_watergirl_2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/fireboy_and_watergirl_2/fireboy_and_watergirl_2.swf',
                'thumbnail' => 'images/Games/fireboyWatergirl2.png',
                'fthumbnail' => 'images/Featured Games/fireboy&watergirl2.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            8 => 
            array (
                'gameID' => 14,
                'gameName' => 'football_legends_2016',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/football_legends_2016/football_legends_2016.swf',
                'thumbnail' => 'images/Games/football.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 450,
            ),
            9 => 
            array (
                'gameID' => 16,
                'gameName' => 'governor_of_poker',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/governor_of_poker/governor_of_poker.swf',
                'thumbnail' => 'images/Games/governorOfPoker.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            10 => 
            array (
                'gameID' => 17,
                'gameName' => 'gun_mayhem',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/gun_mayhem/gun_mayhem.swf',
                'thumbnail' => 'images/Games/gunMayhem.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            11 => 
            array (
                'gameID' => 19,
                'gameName' => 'king_of_fighters_wing_1.8',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/king_of_fighters_wing_1.8/kof-wing-1.8-2.swf',
                'thumbnail' => 'images/Games/theKingOfFighter.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            12 => 
            array (
                'gameID' => 22,
                'gameName' => 'pandemic2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/pandemic2/pandemic2.swf',
                'thumbnail' => 'images/Games/pandemic2.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 700,
                'height' => 500,
            ),
            13 => 
            array (
                'gameID' => 24,
                'gameName' => 'playing_with_fire_2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/playing_with_fire_2/playing_with_fire_2.swf',
                'thumbnail' => 'images/Games/playingWithFire2.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            14 => 
            array (
                'gameID' => 25,
                'gameName' => 'plumber_game',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/plumber_game/plumber_game.swf',
                'thumbnail' => 'images/Games/plumber.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            15 => 
            array (
                'gameID' => 26,
                'gameName' => 'political_duel',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/political_duel/political_duel.swf',
                'thumbnail' => 'images/Games/politicalduel.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            16 => 
            array (
                'gameID' => 27,
                'gameName' => 'road_of_the_dead_2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/road_of_the_dead_2/road_of_the_deads_2.swf',
                'thumbnail' => 'images/Games/Road-of-the-Dead.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            17 => 
            array (
                'gameID' => 28,
                'gameName' => 'scary_maze',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/scary_maze/Scary_Maze_Game.swf',
                'thumbnail' => 'images/Games/scarygame.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            18 => 
            array (
                'gameID' => 31,
                'gameName' => 'swords_and_sandals_2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/swords_and_sandals_2/swords_and_sandals_2.swf',
                'thumbnail' => 'images/Games/swords_and_sandals2.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 800,
                'height' => 600,
            ),
            19 => 
            array (
                'gameID' => 35,
                'gameName' => 'colorball2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/colorball2/colorball2.swf',
                'thumbnail' => 'images/Games/colorball2.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 550,
                'height' => 400,
            ),
            20 => 
            array (
                'gameID' => 36,
                'gameName' => 'crazyflasher4',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/crazyflasher4/crazyflasher4.swf',
                'thumbnail' => 'images/Games/crazyflasher.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 480,
                'height' => 480,
            ),
            21 => 
            array (
                'gameID' => 37,
                'gameName' => 'hungryfish',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/hungryfish/hungryfish.swf',
                'thumbnail' => 'images/Games/hungryfish.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 640,
                'height' => 480,
            ),
            22 => 
            array (
                'gameID' => 39,
                'gameName' => 'linkaball',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/linkaball/linkaball.swf',
                'thumbnail' => 'images/Games/Linkaball.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 500,
                'height' => 500,
            ),
            23 => 
            array (
                'gameID' => 40,
                'gameName' => 'neon2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/neon2/neon2.swf',
                'thumbnail' => 'images/Games/neonRace.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 550,
                'height' => 550,
            ),
            24 => 
            array (
                'gameID' => 41,
                'gameName' => 'planktonlife2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/planktonlife2/planktonlife2.swf',
                'thumbnail' => 'images/Games/planktonLife.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 550,
                'height' => 400,
            ),
            25 => 
            array (
                'gameID' => 42,
                'gameName' => 'poink',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/poink/poink.swf',
                'thumbnail' => 'images/Games/poink.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 400,
                'height' => 500,
            ),
            26 => 
            array (
                'gameID' => 43,
                'gameName' => 'quibeland',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/quibeland/quibeland.swf',
                'thumbnail' => 'images/Games/quibeLand.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 575,
                'height' => 300,
            ),
            27 => 
            array (
                'gameID' => 44,
                'gameName' => 'raidenx',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/raidenx/raidenx.swf',
                'thumbnail' => 'images/Games/raidenX.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 550,
                'height' => 400,
            ),
            28 => 
            array (
                'gameID' => 45,
                'gameName' => 'ratmaze2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/ratmaze2/ratmaze2.swf',
                'thumbnail' => 'images/Games/ratMaza.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 527,
                'height' => 513,
            ),
            29 => 
            array (
                'gameID' => 46,
                'gameName' => 'ratmaze2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/ratmaze2/ratmaze2.swf',
                'thumbnail' => 'images/Games/ratMaza.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 527,
                'height' => 513,
            ),
            30 => 
            array (
                'gameID' => 47,
                'gameName' => 'ratmaze2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/ratmaze2/ratmaze2.swf',
                'thumbnail' => 'images/Games/ratMaza.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 527,
                'height' => 513,
            ),
            31 => 
            array (
                'gameID' => 48,
                'gameName' => 'rebounce',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/rebounce/rebounce.swf',
                'thumbnail' => 'images/Games/rebounce.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 650,
                'height' => 500,
            ),
            32 => 
            array (
                'gameID' => 49,
                'gameName' => 'skillstack',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/skillstack/skillstack.swf',
                'thumbnail' => 'images/Games/skillStack.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 270,
                'height' => 600,
            ),
            33 => 
            array (
                'gameID' => 50,
                'gameName' => 'swarm2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/swarm2/swarm2.swf',
                'thumbnail' => 'images/Games/swarm2.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 600,
                'height' => 600,
            ),
            34 => 
            array (
                'gameID' => 51,
                'gameName' => 'tacticalassassin2',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/tacticalassassin2/tacticalassassin2.swf',
                'thumbnail' => 'images/Games/tacticalAssasin.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 690,
                'height' => 430,
            ),
            35 => 
            array (
                'gameID' => 52,
                'gameName' => 'thing-thing4',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/thing-thing4/thing-thing4.swf',
                'thumbnail' => 'images/Games/thingthing4.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 550,
                'height' => 400,
            ),
            36 => 
            array (
                'gameID' => 53,
                'gameName' => 'xrunning',
                'gameDesc' => '',
                'scoreID' => 0,
                'gameURL' => 'games/xrunning/xrunning.swf',
                'thumbnail' => 'images/Games/xRunning.png',
                'fthumbnail' => 'images/Featured Games/.png',
                'className' => 'NONE',
                'isJar' => 0,
                'width' => 600,
                'height' => 350,
            ),
        ));
        
        
    }
}
